# overlays/clusterA/kustomization.yaml
resources:
  - ../../base
patchesStrategicMerge:
  - deployment-patch.yml


#patches:
  #- target:
    #  kind: Deployment
    #  name: nginx-deployment  # Specify the target resource's name and kind
    #path: deployment-patch.yml
    #patchType: strategic

#patches:
#  - target:
##      kind: Deployment
#      name: nginx-application  # The name of the resource you want to patch
#      namespace: nginx-application  # Optional: Specify the namespace if needed
#    patch: |  # Inline the patch here as a YAML block
#      - op: replace
#        path: /spec/replicas
#        value: 2  # Set the number of replicas for the dev environment

# Update the namePrefix to comply with DNS and RFC rules
#namePrefix: "clustera-"  # Use only lowercase letters and hyphens
