# overlays/clusterA/kustomization.yaml
resources:
  - ../../base

patches:
  - deployment-patch.yml

# Update the namePrefix to comply with DNS and RFC rules
#namePrefix: "clustera-"  # Use only lowercase letters and hyphens
