apiVersion: v1
kind: Namespace
metadata:
  name: nginx-application
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-application
  name: nginx-application
  namespace: nginx-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-application
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-application
    spec:
      containers:
      - image: quay.io/rhdevelopers/bgd:1.0.0
        name: nginx-application
        env:
        - name: COLOR
          value: "blue"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-application
  namespace: nginx-application
spec:
  selector:
    app: nginx-application
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: nginx-application
  name: nginx-application
  namespace: nginx-application
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: nginx-application
    weight: 100
  
